##### JoyOS User Makefile ####

# Name of this project (no spaces or extension)
TARGET = gyrotest

# Source files - list all your .c files here (separated by spaces)
SRC = umain.c

# USB-Serial port number for programming the happyboard
PORT = /dev/ttyUSB0

# Top level JoyOS directory
TOPDIR = ../../

# Extra libraries
EXTRALIBS =

# Include support makefile
include ../makedefaults.inc
