##### JoyOS User Makefile ####

# Name of this project (no spaces or extension)
TARGET = motiontest

# Source files - list all your .c files here (separated by spaces)
SRC = motiontest.c

# USB-Serial port number for programming the happyboard
PORT = com6

# Top level JoyOS directory
TOPDIR = ../../

# Extra libraries
EXTRALIBS = happy

# Include support makefile
include ../makedefaults.inc
