##### JoyOS User Makefile ####

# Name of this project (no spaces or extension)
TARGET = irdisttest

# Source files - list all your .c files here (separated by spaces)
SRC = irdisttest.c

# USB-Serial port number for programming the happyboard
PORT = com6

# Extra libraries
EXTRALIBS = happy

# Top level JoyOS directory
TOPDIR = ../../

# Include support makefile
include ../makedefaults.inc
