##### JoyOS User Makefile ####

# Name of this project (no spaces or extension)
TARGET = robot

# Source files - list all your .c files here (separated by spaces)
SRC = mouse.c stationary.c

# USB-Serial port number for programming the happyboard
PORT = com9

# Top level JoyOS directory
TOPDIR = ../../

# Include support makefile
include ../makedefaults.inc

EXTRALIBS = happy
